# Generated by Django 2.1.15 on 2020-06-06 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='link',
        ),
        migrations.AddField(
            model_name='service',
            name='content',
            field=models.TextField(default='', verbose_name='Contenido'),
        ),
    ]
