# Generated by Django 2.1.15 on 2020-06-06 16:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 6, 16, 33, 17, 300731, tzinfo=utc), verbose_name='Fecha de publicacion'),
        ),
    ]
